version: '3.1'

services:
  backend:
    build: .
    ports:
      - "${BIND_PORT}:${BIND_PORT}"
    env_file: ./.env
    restart: on-failure
    volumes:
      - .:/usr/src/backend/
    depends_on:
      - skanestas_db
    entrypoint: ["python", "backend/app/main.py"]
    container_name: backend

  skanestas_db:
    image: postgres:13
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./dumps:/root/dumps
    environment:
      POSTGRES_DB: "skanestas"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    container_name: skanestas_db

volumes:
  postgres_data: