version: '3.1'

services:
  backend:
    build: .
    ports:
      - "${BIND_PORT}:${BIND_PORT}"
    env_file: ./.env
    restart: on-failure
    volumes:
      - .:/usr/src/backend/
    depends_on:
      - db
    entrypoint: ["python", "backend/app/main.py"]
    healthcheck:
      test: [ "CMD", "curl", "${BIND_IP}:${BIND_PORT}" ]
      retries: 5
      interval: 60s
    container_name: backend

  db:
    image: postgres:13
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file: ./.env
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "${DB_NAME}" ]
      retries: 5
      interval: 5s
    container_name: db

volumes:
  postgres_data: