"""empty message

Revision ID: 24e4e04859d0
Revises: 0c25bc30fbc3
Create Date: 2022-04-24 20:16:07.456275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e4e04859d0'
down_revision = '0c25bc30fbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
