"""empty message

Revision ID: 0c25bc30fbc3
Revises: f994c0ba3f6c
Create Date: 2022-04-24 14:07:46.313090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c25bc30fbc3'
down_revision = 'f994c0ba3f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_change', sa.Column('change_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker_change', 'change_time')
    # ### end Alembic commands ###
