"""empty message

Revision ID: f994c0ba3f6c
Revises: d8dfaf430903
Create Date: 2022-04-24 14:05:52.975256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f994c0ba3f6c'
down_revision = 'd8dfaf430903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_change',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticker_id', sa.BigInteger(), nullable=True),
    sa.Column('change_value', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], name=op.f('fk_ticker_change_ticker_id_ticker')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticker_change'))
    )
    op.create_index(op.f('ix_ticker_change_id'), 'ticker_change', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_change_id'), table_name='ticker_change')
    op.drop_table('ticker_change')
    # ### end Alembic commands ###
