"""empty message

Revision ID: 07cf8386e8c3
Revises: 24e4e04859d0
Create Date: 2022-04-26 19:30:42.401669

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '07cf8386e8c3'
down_revision = '24e4e04859d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('current_value', sa.Numeric(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticker'))
                    )
    op.create_index(op.f('ix_ticker_id'), 'ticker', ['id'], unique=True)
    op.create_table('ticker_change',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('ticker_id', sa.BigInteger(), nullable=True),
                    sa.Column('change_time', sa.DateTime(), nullable=False),
                    sa.Column('change_value', sa.Numeric(), nullable=False),
                    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'],
                                            name=op.f('fk_ticker_change_ticker_id_ticker')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticker_change'))
                    )
    op.create_index(op.f('ix_ticker_change_id'), 'ticker_change', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_change_id'), table_name='ticker_change')
    op.drop_table('ticker_change')
    op.drop_index(op.f('ix_ticker_id'), table_name='ticker')
    op.drop_table('ticker')
    # ### end Alembic commands ###
