"""empty message

Revision ID: b3fe7f538d6d
Revises: 07cf8386e8c3
Create Date: 2022-04-27 14:40:33.330879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3fe7f538d6d'
down_revision = '07cf8386e8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticker_change_id', table_name='ticker_change')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ticker_change_id', 'ticker_change', ['id'], unique=False)
    # ### end Alembic commands ###
