"""empty message

Revision ID: d8dfaf430903
Revises: 
Create Date: 2022-04-24 14:00:57.066036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dfaf430903'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('current_value', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticker'))
    )
    op.create_index(op.f('ix_ticker_id'), 'ticker', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_id'), table_name='ticker')
    op.drop_table('ticker')
    # ### end Alembic commands ###
